### ISSUE TITLE
Attempt to invoke virtual method error

### ISSUE THREAD

**Issue by danbam123** [vsima/uber-java-client#1]
Hi, I am encountering this error when I am trying to use your java wrapper.  

java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
            at com.victorsima.uber.UberClient$2.handleError(UberClient.java:102)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getPriceEstimates(Unknown Source)

The UberClient file is throwing error at the following:  

                .setErrorHandler(new ErrorHandler() {
                    @Override
                    public Throwable handleError(RetrofitError retrofitError) {
                        switch (retrofitError.getResponse().getStatus()) {
                            case 401: //Unauthorized
                                return new UnauthorizedException();
                            case 403: //Forbidden
                                return new ForbiddenException();
                        }
                        return retrofitError;
                    }
                })

I am calling the following method, which is causing the stack trace above:  

  Prices prices = uberClient.getApiService().getPriceEstimates(sourceLatitude, sourceLongitude, destinationLatitude, destinationLongitude);

Can you please help me figure out what's wrong?  I would really appreciate it!  Great work :)

**Comment by DeanWen** [comment]
Did you know how to fix this? I met the same problem

**Comment by vsima** [comment]
@danbam123 @DeanWen can you see if that commit helps ?

**Comment by vsima** [comment]
@DeanWen try the latest version of the library - version 0.0.3. There should be a fix in this release. THanks
