### ISSUE TITLE
Prices Example Support

### ISSUE THREAD

**Issue by danbam123** [vsima/uber-java-client#2]
Hi,

Can I please have a code example of a price estimate request?  Also, do we have to implement the requests on a different thread for this to work or can I use this library directly in the main thread without any problems?  Thank you so much for the help!

**Comment by vsima** [comment]
can you run the tests? please see the price estimates implementation at https://github.com/vsima/uber-java-client/blob/master/src/test/java/com/victorsima/uber/test/BaseTest.java
