### ISSUE TITLE
How can i set the Redirect URI

### ISSUE THREAD

**Issue by ayoola-solomon** [vsima/uber-java-client#4]

**Comment by vsima** [comment]
https://github.com/vsima/uber-java-client/blob/master/src/main/java/com/victorsima/uber/UberClient.java#L178

**Comment by ayoola-solomon** [comment]
I need like a sample app to know what to do... Thanks

**Comment by vsima** [comment]
See the usage section - https://github.com/vsima/uber-java-client#usage
